{
 "title": "Ship Inspector Overview",
 "tags": [
  "observability",
  "opentelemetry"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Poker Operations",
   "type": "timeseries",
   "description": "total metrics recorded by Ship Inspector",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(ship_inspector_poker_equity_calculations_total) + sum(ship_inspector_poker_hand_comparisons_total)",
     "legendFormat": "Total Poker Operations"
    }
   ]
  },
  { "title": "Hand Comparisons", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Hand Comparisons Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ship_inspector_poker_hand_comparisons_total)",
     "legendFormat": "Total Hand Comparisons"
    }
   ]
  },
  {
   "title": "Hand Comparisons by Result",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (result) (ship_inspector_poker_hand_comparisons_total)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  { "title": "Equity Calculations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Equity Calculations Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ship_inspector_poker_equity_calculations_total)",
     "legendFormat": "Total Equity Calculations"
    }
   ]
  },
  {
   "title": "Equity Calculations by Board State",
   "type": "timeseries",
   "description": "Equity calculations by board state: what was the state of the board when equity calculations were requested",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (board_state)(ship_inspector_poker_equity_calculations_total)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Equity Calculations by Equity Calculation",
   "type": "timeseries",
   "description": "Equity calculations by equity calculation: auto, manual, monte carlo",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (calculation_mode)(ship_inspector_poker_equity_calculations_total)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Equity Calculations by Player Count",
   "type": "timeseries",
   "description": "Equity calculations by player count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by (players)(ship_inspector_poker_equity_calculations_total)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}