import type { TableView } from "@common/interfaces/tableInterfaces";

export const timedTable = (serverTime = Date.now()): TableView => ({
  id: "timer-preview",
  version: 1,
  settings: {
    name: "Turn timer",
    maxPlayers: 8,
    smallBlind: 5,
    bigBlind: 10,
    startingStack: 1000,
    turnSeconds: 30,
  },
  isOwner: true,
  yourSeat: 0,
  street: "preflop",
  handNumber: 1,
  button: 5,
  smallBlindSeat: 6,
  bigBlindSeat: 7,
  actor: 0,
  deadline: serverTime + 30000,
  serverTime,
  board: [],
  pot: 15,
  currentBet: 10,
  legal: {
    fold: true,
    check: false,
    call: 10,
    minRaiseTo: 20,
    maxRaiseTo: 1000,
  },
  awards: [],
  events: [],
  canDeal: false,
  closed: false,
  agents: [],
  seats: [
    "Henry",
    "Marina",
    "Vega",
    "Rico",
    "Ziggy",
    "Alex",
    "Sam",
    "Robin",
  ].map((name, seat) => ({
    seat,
    name,
    kind: "human",
    stack: 1000 - (seat === 6 ? 5 : seat === 7 ? 10 : 0),
    bet: seat === 6 ? 5 : seat === 7 ? 10 : 0,
    committed: seat === 6 ? 5 : seat === 7 ? 10 : 0,
    status: "active",
    ready: true,
    sittingOut: false,
    isYou: seat === 0,
    cards:
      seat === 0
        ? [
            { rank: 14, suit: "s" },
            { rank: 13, suit: "s" },
          ]
        : [],
    hasCards: true,
    lastAction: "",
  })),
});
